dist: trusty
language: ruby
before_install:
  - "rm ${BUNDLE_GEMFILE}.lock"
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler -N"
rvm:
  - 2.4.4
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby
