language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 2.4.4
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby
  - truffleruby-head
matrix:
  allow_failures:
    # ruby-head is here because of https://github.com/seattlerb/minitest/pull/862,
    # thanks to @bogdanvlviv for the pointer.
    - rvm: ruby-head
    - rvm: jruby-head
  exclude:
    - arch: ppc64le
      rvm: truffleruby
    - arch: ppc64le
      rvm: truffleruby-head
