language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 2.4.4
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head
  - jruby-head
  - truffleruby
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby
  exclude:
    - arch: ppc64le
      rvm: truffleruby
    - arch: ppc64le
      rvm: truffleruby-head

