language: ruby
rvm:
  - 2.4.4
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby
  - truffleruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: truffleruby-head
    - rvm: truffleruby
